# Generated by Django 4.1.1 on 2022-09-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0002_category_paymentmethod_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bgColor',
            field=models.CharField(default='#C5F1F9', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#0B6F83', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bgColor',
            field=models.CharField(default='#329795', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='color',
            field=models.CharField(default='white', max_length=10),
        ),
    ]
